apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: broker
        env:
        - name: JMX_PORT
          value: ""
        resources:
          limits:
            cpu: "4"
            memory: "2Gi"
          requests:
            cpu: "2"
            memory: "1Gi"
